### ISSUE TITLE
No MeshProduct in pytriqs: ImportError: cannot import name MeshProduct

### ISSUE THREAD

**Issue by henhans** [HugoStrand/pyed#1]
Dear Hugo,

I met the error "ImportError: cannot import name MeshProduct" while running the ipytriqs notebook in ./doc. I have checked the current pytriqs modules but can not find MeshProduct (also the MeshImTime is now located at pytriqs.gf.local.gf). I am wondering which version of triqs should I look for this module?

Thanks very much in advance!
Tsung-Han

**Comment by HugoStrand** [comment]
Dear Tsung-Han,

Thank you for the feedback! The higher order Green's functions requires some new features in `triqs` that currently are on the `triqs/unstable` branch, please install that and try again. I have added info on this dependency in the `pyed` readme file.

Cheers, Hugo
