### ISSUE TITLE
Strange behaviour of the off-diagonal Green function

### ISSUE THREAD

**Issue by yaros72** [HugoStrand/pyed#2]
Dear Hugo,

I found, that off-diagonal Green function has not the correct form in the presence of off-diagonal hoppings. For example, this Hamiltonian:

H = -1*c_dag(0,0)*c(0,1) + -1*c_dag(0,1)*c(0,0) + -1*c_dag(1,0)*c(1,1) + -1*c_dag(1,1)*c(1,0) ,

has such off-diagonal Green function G(tau) between indices (0,0) and (0,1):

![off_diagonal_green_fucntion](https://user-images.githubusercontent.com/9578073/27984541-6e43b830-63e1-11e7-9dd3-9b17022e08fd.png)

As I understand, the Green function should not have negative values.

Thanks very much in advance.
Yaroslav Zhumagulov

**Comment by HugoStrand** [comment]
Dear Yaroslav,

This is not a bug but real physics. 

Only diagonal components of imaginary Green's functions are purely negative. The off-diagonal terms can change sign. 

I have put up [a small tutorial](https://github.com/HugoStrand/pyed/blob/master/benchmark/non_interacting_dimer/Non-interacting%20dimer%20tutorial.ipynb) trying to explain the case for the dimer system. 

Cheers, Hugo

**Comment by yaros72** [comment]
Dear Hugo,

Thank you very much! I realized my mistake, really appreciate the help.

Thanks very much in advance.
Yaroslav Zhumagulov
